services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_HOST=${NUXT_HOST}
      - NUXT_PORT=${NUXT_PORT}
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
    restart: unless-stopped